version: 1
formatters:
  simple:
    format: '[%(asctime)-15s - %(name)s:%(lineno)d - %(levelname)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: logs/project.log
    formatter: simple
    maxBytes: 10240
    backupCount: 3
loggers:
  neural_wsd:
    level: INFO
    propagate: yes
  pytorch_transformers:
    level: WARNING
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console, file]
